apiVersion: v1
kind: Service
metadata:
  name: showcase-claims-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "showcase-insurance-claims.labels" . | nindent 4 }}
spec:
  selector:
    app: showcase-claims-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
