apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: AgenticWorkforce
metadata:
  name: insurance-claims-workforce
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "insurance-claims-showcase.labels" . | nindent 4 }}
spec:
  name: {{ .Values.agenticWorkforce.name | quote }}
  description: {{ .Values.agenticWorkforce.description | quote }}
  owner: {{ .Values.agenticWorkforce.owner | quote }}
  tags:
    {{- toYaml .Values.agenticWorkforce.tags | nindent 4 }}
  entryPointAgents:
    {{- range .Values.agenticWorkforce.entryPointAgents }}
    - name: {{ . }}
    {{- end }}
