apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./observability-dashboard
  - ./librechat
  - ./n8n
  - lgtm.yaml
  - ./agentic-layer
  - otel-tempo-config.yaml
