apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: showcase-insurance-claims
resources:
  - namespace.yaml
  - claims-voice-agent.yaml
  - claims-analysis-agent.yaml
  - showcase-claims-frontend.yaml
  - customer-database.yaml
  - insurance-claims-workforce.yaml
  - mongodb.yaml
  - claims-database.yaml
  - claims-api.yaml
